language: php
php:
  - 7.1
  - 7.2
  - nightly
script: ./vendor/bin/phpunit --coverage-text
install:
    - composer self-update
    - composer update --prefer-dist
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly